# Copyright 2024-2026 Tymofii Pidlisnyi. Apache-2.0 license. See LICENSE.
"""Build B cross-language fixtures — Python implementation matches TS.

Loads the JSON fixtures at tests/v2/fixtures/build-b/ (vendored from the
canonical build-b fixture set) and asserts that compute_data_axis_weights
/ compute_compute_axis_weights / hash_weight_profile produce output
byte-identical to the pinned expected values (which were generated by the
TypeScript SDK).
"""

import json
import os
from pathlib import Path

import pytest

from agent_passport.v2.attribution_weights import (
    compute_compute_axis_weights,
    compute_data_axis_weights,
    hash_weight_profile,
)

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "build-b"


def _load_fixtures():
    if not FIXTURE_DIR.exists():
        pytest.skip(f"fixture dir missing: {FIXTURE_DIR}")
    fixtures = []
    for p in sorted(FIXTURE_DIR.glob("*.json")):
        with p.open() as f:
            fixtures.append((p.name, json.load(f)))
    return fixtures


FIXTURES = _load_fixtures() if FIXTURE_DIR.exists() else []


def test_fixture_count_matches_spec():
    assert len(FIXTURES) == 10, f"expected 10 fixtures, got {len(FIXTURES)}"


@pytest.mark.parametrize("name,data", FIXTURES, ids=[f[0] for f in FIXTURES] if FIXTURES else [])
def test_fixture_matches_pinned_expected_output(name, data):
    kind = data["kind"]
    if kind == "d_axis":
        actual = compute_data_axis_weights(
            data["input"]["sources"],
            action_timestamp=data["input"]["action_timestamp"],
        )
        assert actual == data["expected"]["weights"], f"{name}: D-axis output diverged"
    elif kind == "c_axis":
        actual = compute_compute_axis_weights(data["input"]["providers"])
        assert actual == data["expected"]["weights"], f"{name}: C-axis output diverged"
    elif kind == "profile_hash":
        actual = hash_weight_profile(data["input"]["profile"])
        assert actual == data["expected"]["hash"], f"{name}: profile hash diverged"
    else:
        pytest.fail(f"unknown fixture kind: {kind}")
