# Copyright 2024-2026 Tymofii Pidlisnyi. Apache-2.0 license. See LICENSE.
"""Build C — cross-language verification from Python side.

Loads specs/fixtures/build-c/*.json (generated by the TS
scripts/generate-build-c-fixtures.ts) and proves:

  (a) the pinned record verifies under the pinned gateway public key,
  (b) aggregating the pinned input_receipts in Python produces a
      byte-identical record (settlement_record_hash match),
  (c) every pinned contributor_query_response verifies,
  (d) Python-rebuilt contributor queries match TS-generated ones
      byte-for-byte.

This is the interop proof: canonicalization, Merkle, and signature
construction are byte-identical across TypeScript and Python.
"""

import json
from pathlib import Path

import pytest

from agent_passport.v2.attribution_settlement import (
    aggregate_attribution_primitives,
    build_contributor_query_response,
    settlement_record_hash,
    verify_contributor_query_response,
    verify_settlement_record,
)


FIXTURE_DIR = Path("/Users/tima/aeoess_web/specs/fixtures/build-c")


def _load_fixtures():
    return sorted(FIXTURE_DIR.glob("*.json"))


def test_build_c_fixtures_present():
    fixtures = _load_fixtures()
    assert len(fixtures) == 5, f"expected 5 fixtures, got {len(fixtures)}"


@pytest.mark.parametrize("path", _load_fixtures(), ids=lambda p: p.name)
def test_build_c_fixture_verifies(path):
    data = json.loads(path.read_text())
    verdict = verify_settlement_record(
        data["expected_record"],
        gateway_public_key_hex=data["gateway_public_key"],
        input_receipts=data["input_receipts"],
    )
    assert verdict["valid"], f"{path.name}: {verdict}"


@pytest.mark.parametrize("path", _load_fixtures(), ids=lambda p: p.name)
def test_build_c_fixture_regenerates_bytes(path):
    data = json.loads(path.read_text())
    unsigned = aggregate_attribution_primitives(
        data["input_receipts"], data["period"],
        gateway_did=data["gateway_did"],
        issued_at=data["expected_record"]["issued_at"],
    )
    expected_hash = settlement_record_hash(data["expected_record"])
    re_hash = settlement_record_hash(unsigned)
    assert re_hash == expected_hash, f"{path.name}: Python regenerated hash differs"


@pytest.mark.parametrize("path", _load_fixtures(), ids=lambda p: p.name)
def test_build_c_fixture_contributor_queries_verify(path):
    data = json.loads(path.read_text())
    for q in data.get("contributor_queries", []):
        if not q.get("response"):
            continue
        verdict = verify_contributor_query_response(
            q["response"], gateway_public_key_hex=data["gateway_public_key"]
        )
        assert verdict["valid"], f"{path.name}: {q['contributor_did']}: {verdict}"


@pytest.mark.parametrize("path", _load_fixtures(), ids=lambda p: p.name)
def test_build_c_fixture_rebuilt_queries_byte_identical(path):
    data = json.loads(path.read_text())
    record = data["expected_record"]
    for q in data.get("contributor_queries", []):
        regenerated = build_contributor_query_response(record, q["contributor_did"])
        if not q.get("response"):
            assert regenerated is None
            continue
        assert json.dumps(regenerated, sort_keys=True) == json.dumps(q["response"], sort_keys=True), (
            f"{path.name}: {q['contributor_did']} rebuilt query diverged"
        )
